# YOUR NAME OR TITLE OF YOUR SITE
name: Isaac Ang

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Isaac. I'm a Final-Year Cybersecurity Student currently based in Singapore. Founding member in an early stage startup, AdSwift, and looking to bootstrap more projects. Apart from tech, I'm a passionate Muay Thai athlete, photographer, writer, and horology lover. Always finding ways to better my game.

# YOUR/BRAND IMAGE URL
Image_URL: https://avatars.githubusercontent.com/u/64346571?s=400&u=f1ac0d6a665e36aa27795cb4395fc4f050845621&v=4

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://i.imgur.com/GurLu6u.jpg

# SOCIAL MEDIA
links:
  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

  # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in/isaacangth/
    Username: isaacangth
    Color: "#2867B2"
    Icon-Class: fab fa-linkedin-in

  # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com/killedbythecircus/
    Username: killedbythecircus
    Color: "#DD2A7B"
    Icon-Class: fab fa-instagram

    # GITHUB
  - Name: GitHub
    URL: https://github.com/BackToReal1ty
    Username: BackToReal1ty
    Color: "#6e5494"
    Icon-Class:
      fab fa-github

      # GITLAB
  - Name: GitLab
    URL: https://gitlab.com/surprisedpikachuu
    Username: surprisedpikachuu
    Color: "#6e5494"
    Icon-Class: fab fa-github

    # REDDIT
  - Name: Reddit
    URL: https://www.reddit.com/user/BackToReal1ty
    Username: BackToReal1ty
    Color: "#FF4500"
    Icon-Class: fab fa-reddit-alien

  # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me/surprisedpikachu
    Username: surprisedpikachu
    Color: "#0088cc"
    Icon-Class: fab fa-telegram-plane

    # WHATSAPP
  - Name: WhatsApp
    URL: https://wa.me/6581499409
    Username: "+6581499409"
    Color: "#25d366"
    Icon-Class: fab fa-whatsapp

  # DISCORD
  - Name: Discord
    URL: https://discord.com/users/292612985720143872
    Username: speakeasy#2055
    Icon-Class: fab fa-discord
    Color: "#5865F2"
    Text_Color: "#ffffff"

    # EMAIL
  - Name: Email
    URL: "mailto:isaac@helloisaac.me"
    Icon-Class: fas fa-envelope
    Color: "#e17055"
    Text_Color: "#ffffff"

  # SPOTIFY
  - Name: Spotify
    URL: https://open.spotify.com/user/21drcjkdjnlvo6a7z5xqs2usi?si=cb316de9c9bf499e
    Username:
    Color: "#1DB954"
    Icon-Class: fab fa-spotify

  # # FIGMA
  # - Name: Figma
  #   URL: https://www.figma.com
  #   Username: "@harshtrivedi"
  #   Icon-Class: fab fa-figma
  #   Color: "#ff2865"
  #   Text_Color: "#ffffff"

  # # MEDIUM
  # - Name: Medium
  #   URL: "https://medium.com"
  #   Username: "@harsh98trivedi"
  #   Icon-Class: fab fa-medium-m
  #   Color: "#00ab6c"
  #   Text_Color: "#ffffff"

  #   # DEV.TO
  # - Name: Dev.to
  #   URL: "https://dev.to"
  #   Username: harsh98trivedi
  #   Icon-Class: fab fa-dev
  #   Color: "#ffffff"
  #   Text_Color: "#000000"

  # # CUSTOM LINK
  # - Name: Blog
  #   URL: https://harsh98trivedi.github.io/blog
  #   Icon-Class: fas fa-link
  #   Color: "#ffb142"
  #   Text_Color: "#ffffff"

  # # Cal.com
  # - Name: Cal.com
  #   URL:
  #   Username: harshtrivedi
  #   Color: "#232323"
  #   Icon-Class: fa fa-calendar-check

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
