# YOUR NAME OR TITLE OF YOUR SITE
name: Isaac Ang

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Isaac. I'm a Final-Year Cybersecurity Student currently based in Singapore. Founding member in an early stage startup, AdSwift, and looking to bootstrap more projects. Apart from tech, I'm a passionate Muay Thai athlete, photographer, writer, and horology lover. Always finding ways to better my game.

# YOUR/BRAND IMAGE URL
Image_URL: https://i.imgur.com/vN5Mg3c.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://i.imgur.com/GurLu6u.jpg

# SOCIAL MEDIA
links:
  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

  # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in/isaacangth/
    Username: isaacangth
    Color: "#2867B2"
    Icon-Class: fab fa-linkedin-in

  # INSTAGRAM
  - Name: Instagram
    URL:
    Username: harsh98trivedi
    Color: "#DD2A7B"
    Icon-Class: fab fa-instagram

    # Cal.com
  - Name: Cal.com
    URL:
    Username: harshtrivedi
    Color: "#232323"
    Icon-Class: fa fa-calendar-check

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCS3zvA_2r1iGT7MB3NVCGAw
    Color: "#ff0000"
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: harsh98trivedi
    Color: "#6e5494"
    Icon-Class:
      fab fa-github

      # GITLAB
  - Name: GitLab
    URL: http://github.com
    Username: harsh98trivedi
    Color: "#6e5494"
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: "mailto:harshtrivedi@duck.com"
    Icon-Class: fas fa-envelope
    Color: "#e17055"
    Text_Color: "#ffffff"

    # TWITCH
  - Name: Twitch
    URL: "https://twitch.tv"
    Username: harsh98trivedi
    Icon-Class: fab fa-twitch
    Color: "#9147fe"
    Text_Color: "#ffffff"

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: harshtrivedi
    Color: "#FF4500"
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

  # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: theharshtrivedi
    Color: "#0088cc"
    Icon-Class: fab fa-telegram-plane

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username:
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'
  # FIGMA
  - Name: Figma
    URL: https://www.figma.com
    Username: "@harshtrivedi"
    Icon-Class: fab fa-figma
    Color: "#ff2865"
    Text_Color: "#ffffff"

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: 314ihryk3edvtusti6il3oy3x5da
    Color: "#1DB954"
    Icon-Class: fab fa-spotify

  # # MEDIUM
  # - Name: Medium
  #   URL: "https://medium.com"
  #   Username: "@harsh98trivedi"
  #   Icon-Class: fab fa-medium-m
  #   Color: "#00ab6c"
  #   Text_Color: "#ffffff"

  #   # DEV.TO
  # - Name: Dev.to
  #   URL: "https://dev.to"
  #   Username: harsh98trivedi
  #   Icon-Class: fab fa-dev
  #   Color: "#ffffff"
  #   Text_Color: "#000000"

  # # CUSTOM LINK
  # - Name: Blog
  #   URL: https://harsh98trivedi.github.io/blog
  #   Icon-Class: fas fa-link
  #   Color: "#ffb142"
  #   Text_Color: "#ffffff"

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
